version: '3.7'

services:
  web:
    build:
      context: ./../../
      dockerfile: docker/dev/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - weather_finder.env
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"

